services:
  app:
    image: golang:1.22
    container_name: go_app
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app
    command: go run main.go
    ports:
      - "8080:8080"
 # sudo docker run -it 2fce09cfad57 bash