version: "3.9"

services:
  goapp:
    dns:
        - 8.8.8.8
        - 1.1.1.1  
    build: .
    container_name: go-dev
    stdin_open: true     # ← attach有効
    tty: true            # ← attach有効
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
